### ISSUE TITLE
Issue with Required Subaccounts Field on Initializing Payment

### ISSUE THREAD

**Issue by abdiu34567** [fireayehu/chapa-nodejs#1] opened 2023-05-24 14:02 UTC
I encountered an issue while attempting to initialize a payment using the chapa-node.js library. According to the documentation, the subaccounts field is optional. However, it is treated as a required field during the payment initialization process.

Even after providing the id field within the subaccounts array, the payment initialization still fails with the following error:

{
  "success": false,
  "error": "subaccounts must be an object type, but the final value was: null (cast from the value [\n  {\n    \"id\": \"\\\"80a510ea-7497-4499-8b49-ac13a3ab7d07\\\"\"\n  }\n]).\n If \"null\" is intended as an empty value, be sure to mark the schema as `.nullable()`."
}

**Comment by fireayehu** [comment] 2023-06-04 05:46
@abdiu34567 The issue is now fixed on the new release 1.3.0

**Closed as completed** 2023-06-04 05:47 UTC
